ALTER TABLE "Mesa" ALTER COLUMN "estadoId" SET DEFAULT 1;
ALTER TABLE "Pedido" ALTER COLUMN "estadoId" SET DEFAULT 1;
ALTER TABLE "Pedido" ALTER COLUMN "estadoCocinaId" SET DEFAULT 1;
ALTER TABLE "Cuenta" ALTER COLUMN "metodoPagoId" SET DEFAULT 1;
ALTER TABLE "Cuenta" ALTER COLUMN "estadoId" SET DEFAULT 1;
